10-31 22:39:57 database: opening D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo
org.h2.jdbc.JdbcSQLException: IO Exception: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。) [90028-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.convert(Message.java:368)
	at org.h2.store.FileStore.<init>(FileStore.java:66)
	at org.h2.store.FileStore.open(FileStore.java:45)
	at org.h2.store.FileStore.open(FileStore.java:37)
	at org.h2.engine.Database.openFile(Database.java:298)
	at org.h2.store.LogFile.<init>(LogFile.java:62)
	at org.h2.store.LogFile.openIfLogFile(LogFile.java:86)
	at org.h2.store.LogSystem.loadActiveLogFiles(LogSystem.java:211)
	at org.h2.store.LogSystem.<init>(LogSystem.java:50)
	at org.h2.engine.Database.open(Database.java:426)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:76)
	at java.lang.Thread.run(Thread.java:595)
Caused by: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:212)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:98)
	at org.h2.util.FileUtils.openRandomAccessFile(FileUtils.java:41)
	at org.h2.store.FileStore.<init>(FileStore.java:63)
	... 13 more
10-31 22:39:57 database: opening D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo
org.h2.jdbc.JdbcSQLException: IO Exception: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。) [90028-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.convert(Message.java:368)
	at org.h2.store.FileStore.<init>(FileStore.java:66)
	at org.h2.store.FileStore.open(FileStore.java:45)
	at org.h2.store.FileStore.open(FileStore.java:37)
	at org.h2.engine.Database.openFile(Database.java:298)
	at org.h2.store.LogFile.<init>(LogFile.java:62)
	at org.h2.store.LogFile.openIfLogFile(LogFile.java:86)
	at org.h2.store.LogSystem.loadActiveLogFiles(LogSystem.java:211)
	at org.h2.store.LogSystem.<init>(LogSystem.java:50)
	at org.h2.engine.Database.open(Database.java:426)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:76)
	at java.lang.Thread.run(Thread.java:595)
Caused by: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:212)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:98)
	at org.h2.util.FileUtils.openRandomAccessFile(FileUtils.java:41)
	at org.h2.store.FileStore.<init>(FileStore.java:63)
	... 13 more
10-31 22:40:37 database: opening D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo
org.h2.jdbc.JdbcSQLException: IO Exception: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。) [90028-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.convert(Message.java:368)
	at org.h2.store.FileStore.<init>(FileStore.java:66)
	at org.h2.store.FileStore.open(FileStore.java:45)
	at org.h2.store.FileStore.open(FileStore.java:37)
	at org.h2.engine.Database.openFile(Database.java:298)
	at org.h2.store.LogFile.<init>(LogFile.java:62)
	at org.h2.store.LogFile.openIfLogFile(LogFile.java:86)
	at org.h2.store.LogSystem.loadActiveLogFiles(LogSystem.java:211)
	at org.h2.store.LogSystem.<init>(LogSystem.java:50)
	at org.h2.engine.Database.open(Database.java:426)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:76)
	at java.lang.Thread.run(Thread.java:595)
Caused by: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:212)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:98)
	at org.h2.util.FileUtils.openRandomAccessFile(FileUtils.java:41)
	at org.h2.store.FileStore.<init>(FileStore.java:63)
	... 13 more
10-31 22:41:08 database: opening D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo
org.h2.jdbc.JdbcSQLException: IO Exception: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。) [90028-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.convert(Message.java:368)
	at org.h2.store.FileStore.<init>(FileStore.java:66)
	at org.h2.store.FileStore.open(FileStore.java:45)
	at org.h2.store.FileStore.open(FileStore.java:37)
	at org.h2.engine.Database.openFile(Database.java:298)
	at org.h2.store.LogFile.<init>(LogFile.java:62)
	at org.h2.store.LogFile.openIfLogFile(LogFile.java:86)
	at org.h2.store.LogSystem.loadActiveLogFiles(LogSystem.java:211)
	at org.h2.store.LogSystem.<init>(LogSystem.java:50)
	at org.h2.engine.Database.open(Database.java:426)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:76)
	at java.lang.Thread.run(Thread.java:595)
Caused by: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:212)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:98)
	at org.h2.util.FileUtils.openRandomAccessFile(FileUtils.java:41)
	at org.h2.store.FileStore.<init>(FileStore.java:63)
	... 13 more
10-31 22:43:23 database: opening D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo
org.h2.jdbc.JdbcSQLException: IO Exception: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。) [90028-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.convert(Message.java:368)
	at org.h2.store.FileStore.<init>(FileStore.java:66)
	at org.h2.store.FileStore.open(FileStore.java:45)
	at org.h2.store.FileStore.open(FileStore.java:37)
	at org.h2.engine.Database.openFile(Database.java:298)
	at org.h2.store.LogFile.<init>(LogFile.java:62)
	at org.h2.store.LogFile.openIfLogFile(LogFile.java:86)
	at org.h2.store.LogSystem.loadActiveLogFiles(LogSystem.java:211)
	at org.h2.store.LogSystem.<init>(LogSystem.java:50)
	at org.h2.engine.Database.open(Database.java:426)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:76)
	at java.lang.Thread.run(Thread.java:595)
Caused by: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:212)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:98)
	at org.h2.util.FileUtils.openRandomAccessFile(FileUtils.java:41)
	at org.h2.store.FileStore.<init>(FileStore.java:63)
	... 13 more
10-31 22:43:33 database: opening D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo
org.h2.jdbc.JdbcSQLException: IO Exception: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。) [90028-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.convert(Message.java:368)
	at org.h2.store.FileStore.<init>(FileStore.java:66)
	at org.h2.store.FileStore.open(FileStore.java:45)
	at org.h2.store.FileStore.open(FileStore.java:37)
	at org.h2.engine.Database.openFile(Database.java:298)
	at org.h2.store.LogFile.<init>(LogFile.java:62)
	at org.h2.store.LogFile.openIfLogFile(LogFile.java:86)
	at org.h2.store.LogSystem.loadActiveLogFiles(LogSystem.java:211)
	at org.h2.store.LogSystem.<init>(LogSystem.java:50)
	at org.h2.engine.Database.open(Database.java:426)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:76)
	at java.lang.Thread.run(Thread.java:595)
Caused by: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:212)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:98)
	at org.h2.util.FileUtils.openRandomAccessFile(FileUtils.java:41)
	at org.h2.store.FileStore.<init>(FileStore.java:63)
	... 13 more
10-31 22:52:18 database: opening D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo
org.h2.jdbc.JdbcSQLException: IO Exception: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。) [90028-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.convert(Message.java:368)
	at org.h2.store.FileStore.<init>(FileStore.java:66)
	at org.h2.store.FileStore.open(FileStore.java:45)
	at org.h2.store.FileStore.open(FileStore.java:37)
	at org.h2.engine.Database.openFile(Database.java:298)
	at org.h2.store.LogFile.<init>(LogFile.java:62)
	at org.h2.store.LogFile.openIfLogFile(LogFile.java:86)
	at org.h2.store.LogSystem.loadActiveLogFiles(LogSystem.java:211)
	at org.h2.store.LogSystem.<init>(LogSystem.java:50)
	at org.h2.engine.Database.open(Database.java:426)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:76)
	at java.lang.Thread.run(Thread.java:595)
Caused by: java.io.FileNotFoundException: D:\USER\workspace2\s2jdbc-tutorial\h2\data\demo.0.log.db (アクセスが拒否されました。)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:212)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:98)
	at org.h2.util.FileUtils.openRandomAccessFile(FileUtils.java:41)
	at org.h2.store.FileStore.<init>(FileStore.java:63)
	... 13 more
